import "./globals.css";
import { Inter } from "next/font/google";

import { NavBar, Footer } from "../Components";
import { CrowFundingProvider } from "../Context/Crowfunding";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body>
          <CrowFundingProvider>
            <NavBar />
            {children}
            <Footer />
          </CrowFundingProvider>
        </body>
      </html>
  );
}
